version: '3.6'
services:
    database:
        container_name: mysql
        platform: linux/x86_64
        build: .
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        volumes:
            - db-volume:/var/lib/mysql
        networks:
            - rede-sgdb
volumes:
    db-volume:

networks:
  rede-sgdb:
    driver: bridge